USE ROLE ACCOUNTADMIN;

CREATE OR REPLACE ROLE ML_ENGINEER;
BEGIN
    LET current_user_name := CURRENT_USER();
    EXECUTE IMMEDIATE 'GRANT ROLE ML_ENGINEER TO USER ' || current_user_name;
END;

GRANT CREATE DATABASE ON ACCOUNT TO ROLE ML_ENGINEER;
GRANT BIND SERVICE ENDPOINT ON ACCOUNT TO ROLE ML_ENGINEER;
GRANT CREATE ROLE ON ACCOUNT TO ROLE ML_ENGINEER;
GRANT CREATE WAREHOUSE ON ACCOUNT TO ROLE ML_ENGINEER;
GRANT MANAGE GRANTS ON ACCOUNT TO ROLE ML_ENGINEER;
GRANT CREATE INTEGRATION ON ACCOUNT TO ROLE ML_ENGINEER;
GRANT CREATE APPLICATION PACKAGE ON ACCOUNT TO ROLE ML_ENGINEER;
GRANT CREATE APPLICATION ON ACCOUNT TO ROLE ML_ENGINEER;
GRANT IMPORT SHARE ON ACCOUNT TO ROLE ML_ENGINEER;

USE ROLE ML_ENGINEER;

CREATE OR REPLACE DATABASE SNOW_ML_DB;
GRANT ALL ON DATABASE SNOW_ML_DB TO ROLE ML_ENGINEER;

CREATE OR REPLACE SCHEMA SNOW_ML_SCHEMA;

CREATE OR REPLACE WAREHOUSE SNOW_ML_PIPELINE 
    WAREHOUSE_TYPE = 'SNOWPARK-OPTIMIZED'
    WAREHOUSE_SIZE = "MEDIUM"
    AUTO_SUSPEND = 10000
    AUTO_RESUME = TRUE
    COMMENT = 'Warehouse to work on end-to-end ML pipeline'
;

GRANT CREATE NOTEBOOK ON SCHEMA SNOW_ML_DB.SNOW_ML_SCHEMA TO ROLE "ML_ENGINEER";

GRANT CREATE STAGE ON SCHEMA SNOW_ML_DB.SNOW_ML_SCHEMA TO ROLE "ML_ENGINEER";

CREATE STAGE IF NOT EXISTS boats_stage
    DIRECTORY = (ENABLE = true)
    ENCRYPTION = (TYPE = 'SNOWFLAKE_SSE');